# Generated by Django 2.2.7 on 2020-01-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_phone',
            field=models.IntegerField(),
        ),
    ]
