# Generated by Django 2.2.7 on 2020-01-16 16:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200116_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
