# Generated by Django 2.2.7 on 2020-01-17 11:52

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200116_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('host_email', models.EmailField(max_length=254)),
                ('host_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('checkin', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('inside', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
