# Generated by Django 2.2.7 on 2020-01-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
